### ISSUE TITLE
should it be working in Mage 1.9?

### ISSUE THREAD

**Issue by janw-oostendorp** [pug-more/mageploy#12]
I installed it correctly. But changes don't seem to appear.  
I tried to change a cms block.

**Comment by aleron75** [comment]
Hi,
I just installed it on clean 1.9.1.0 and changed both a CMS Page and Block and actions were tracked correctly.

Do you see the blue bar on top of your Admin Panel like the one in the attached screen shot?

What is the output if you execute the following command from Magento's root?

$ php shell/mageploy.php -s

![selection_001](https://cloud.githubusercontent.com/assets/1199894/6593622/6d8a80b8-c7da-11e4-9980-20e6f6432916.png)

Let me know.

**Comment by janw-oostendorp** [comment]
Hi Aleron,

Thanks for the reply. I've never seen that bar in the installation(s).

The `PugMoRe_Mageploy` is listed in the advance section and active.
In the dev settings it's active and so is debug mode.
Cache is disabled and flushed.

The status is: `php shell/mageploy.php -s`

    Mageploy v 1.1.11 - tracking is active - user is test1
    There aren't any pending actions to execute.

To extend the test I removed all `app/etc/modules` except the `Mage_*.xml` and `PugMoRe_Mageploy.xml`

No classes are locally overwritten.

**Comment by aleron75** [comment]
Do you have `mageploy_all.csv` and `mageploy_executed.csv` files under `<mage_basedir>/var/mageploy/`? Are they empty?

**Comment by janw-oostendorp** [comment]
Both exist and are empty

**Comment by aleron75** [comment]
If they are empty Mageploy is not tracking despite the status tells the contrary.

Provided you enabled logs, do you see anything in `PugMoRe_Mageploy.log`?

Check for file permissions then I suggest to try on a clean installation.

Kind regards
