### ISSUE TITLE
Executed list should be stored in Database

### ISSUE THREAD

**Issue by amenk** [pug-more/mageploy#16]
The changes Mageploy trackst do effect the database.
So the executed list should be in the database instead of a file. Reason: If I reimport the database, the tasks should be executed again.

**Comment by amenk** [comment]
What do you think about my commit?
I am using the timestamp as a identifier to track whether an action was executed. Maybe we should generate another unique identifier.

**Comment by aleron75** [comment]
I used timestamp in files because I assumed different environments use different file system locations.
If we can assume the same for DB (different environments use different DBs) using a timestamp should be ok.
About your commit: I didn't tested it so far, reading code it sounds good.

**Comment by amenk** [comment]
I don't fully get what you are writing. My motivation to store the done-List in Database is that we often import a fresh database and I want the tasks to be executed then.

**Comment by aleron75** [comment]
Hi @amenk, your motivation sounds good, you did well.

**Comment by amenk** [comment]
Thanks. I think I will clean/remove file-storage for the done list

**Comment by aleron75** [comment]
We can close the issue as soon as we decide whether to create a branch not to cause backwards compatibility issues.
What do you think about it?

**Comment by amenk** [comment]
I would opt for creating a dev-2.0 branch

**Comment by aleron75** [comment]
>I would opt for creating a dev-2.0 branch

good, can you create the branch and make the pull request?

**Comment by amenk** [comment]
I think I can only make a PR to an existing branch

**Comment by aleron75** [comment]
just created the "dev-2.0" branch, let me know if there are any issues
sincerely,
Alessandro

**Comment by aleron75** [comment]
Merged and tested on dev-2.0 branch thus I close this issue.
