### ISSUE TITLE
Change storage to single files

### ISSUE THREAD

**Issue by amenk** [pug-more/mageploy#19]
I would like to drop CSV files and store changes in single files with the name $TIMESTAMP.php

The file then would contain an array with the data (created using `var_export($foo, true)`).

Advantages:

1. No more merge conflicts if two people add a line to the CSV file 
2. The whole change would not be in on single line and is so easier to review

**Comment by aleron75** [comment]
I would suggest differentiating single file names between environments; even if it can be rare, a timestamp collision may occur.

Say $TIMESTAMP-$ENV_ID or something like this

What do you think about it?

**Comment by amenk** [comment]
you mean the user name? Yes we can do that.
But I am using microseconds timestamps, a collision is (almost) impossible :)

**Comment by aleron75** [comment]
>But I am using microseconds timestamps, a collision is (almost) impossible :)

I apologize but I've read the Black Swan by Taleb so I tend to be pessimistic about "things that should not happen" :-)

**Comment by amenk** [comment]
Is it a good book?

**Comment by aleron75** [comment]
N. N. Taleb is that kind of authors you will love or hate. Consider I'm basing my choices in work and life based on some of his visions. I suggest to give him a try.

**Comment by aleron75** [comment]
Merged and tested on branch dev-2.0, seems to work properly thus I close issue.
