### ISSUE TITLE
Mageploy and Magento CE 1.9.2.1

### ISSUE THREAD

**Issue by taaz** [pug-more/mageploy#23]
Installation works and tracking seems to be active.
Unfortunately, nothing will be tracked.

Also tested with the same steps under Magento CE 1.9.1.0, there it works.

**Comment by taaz** [comment]
After some debugging I found out, that this was not an issue with Magento CE 1.9.2.1, but with the frontName of the admin panel I chose for this new install.
I created a pull request (#24) which fixes this problem.

**Comment by aleron75** [comment]
I merged the pull request, thus I close this issue, thank you again.
