### ISSUE TITLE
Consider clear text storage / or even PHP code generation

### ISSUE THREAD

**Issue by amenk** [pug-more/mageploy#3]
Currently content, for example of CMS blocks, is stored in an encoded format.

If there happen to be conflicts, this is hard to resolve in git diffs.

Can we use maybe another format there? XML or yaml?

**Comment by amenk** [comment]
It's that simple:

https://github.com/iMi-digital/mageploy/commit/0c5d8eb5bf99d9b575665c39452ec899cc3ecd23

Shall I create a pull request?

**Comment by amenk** [comment]
Actually it is not that simple :( will try more.

**Comment by aleron75** [comment]
@amenk the reason I used the base64 encoding is to get rid of carriage return problems; I don't know whether json_encode would fit as well but feel free to contribute to the project as you like;
sincerely,
Alessandro

**Comment by amenk** [comment]
JSON encode writes `\n` or `\n\r`

**Comment by amenk** [comment]
Do you care a about backwards compat? Or can we just change it to JSON? Otherwise we would have to make a setting.

**Comment by aleron75** [comment]
I don't care about backwards compatibility too much provided we tag different versions.
What do you think?

**Comment by amenk** [comment]
but then we would have to add compat code for loading from older versions

**Comment by aleron75** [comment]
let's make a branch for v2 then, does it sound a better choice?

**Comment by aleron75** [comment]
Created branch dev-2.0 and implemented there by @amenk thus I close this issue
